local_repository(
    name = "bazel_lib",
    path = "../..",
)

load("@bazel_lib//lib:repositories.bzl", "bazel_lib_dependencies")

bazel_lib_dependencies()

load(":test_extension.bzl", "test_repo")

test_repo(name = "test")
