load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "6e78f0e57de26801f6f564fa7c4a48dc8b36873e416257a92bbb0937eeac8446",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

local_repository(
    name = "bazel_lib",
    path = "../..",
)

load("@bazel_lib//lib:repositories.bzl", "bazel_lib_dependencies", "register_coreutils_toolchains")

bazel_lib_dependencies()

# Registering coreutils is required under WORKSPACE for the copy action to work
# Under bzlmod, this is done automatically by just depending on the bazel-lib module.
register_coreutils_toolchains()
