local_repository(
    name = "aspect_bazel_lib",
    path = "../../..",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies", "register_tar_toolchains")

aspect_bazel_lib_dependencies()

register_tar_toolchains()

local_repository(
    name = "repo1",
    path = "../repo1",
)
