#!/usr/bin/env bash
set -euo pipefail

# This test verifies that .bat files generated by diff_test have CRLF line endings
# This is critical on Windows due to a cmd.exe bug where labels aren't found
# when files >~4KB have LF-only line endings.
# See: https://www.dostips.com/forum/viewtopic.php?t=8988

# Load runfiles library to resolve paths
# shellcheck disable=SC1090
source "$RUNFILES_DIR/_main/external/bazel_tools/tools/bash/runfiles/runfiles.bash"

if [[ $# -lt 1 ]]; then
    echo "ERROR: Expected test file path as argument"
    exit 1
fi

test_file="$1"

# On Windows, the test file will be a .bat file
# On other platforms, it will be a .sh file and we skip this test
if [[ "$test_file" != *.bat ]]; then
    echo "SKIP: Test file is not a .bat file: $test_file"
    exit 0
fi

# Resolve the runfile path
bat_file="$(rlocation "$test_file")"

if [[ ! -f "$bat_file" ]]; then
    echo "ERROR: Could not find $bat_file"
    exit 1
fi

echo "Checking line endings in: $bat_file"

# Check if the file contains CRLF line endings
# We use od to check for the presence of \r\n (0x0d 0x0a)
if ! od -An -tx1 "$bat_file" | grep -q "0d 0a"; then
    echo "ERROR: $bat_file does not contain CRLF (\\r\\n) line endings"
    echo "File may have LF-only line endings, which causes cmd.exe parsing issues on Windows"
    exit 1
fi

# Additionally verify that we don't have double CRLF (\r\r\n or \r\n\n)
if od -An -tx1 "$bat_file" | grep -q "0d 0d 0a"; then
    echo "ERROR: $bat_file contains double carriage returns (\\r\\r\\n)"
    exit 1
fi

if od -An -tx1 "$bat_file" | grep -q "0d 0a 0a"; then
    echo "ERROR: $bat_file contains CRLF followed by LF (\\r\\n\\n)"
    exit 1
fi

echo "SUCCESS: $bat_file has correct CRLF line endings"
exit 0
