local_repository(
    name = "bazel_lib",
    path = "../..",
)

load("@bazel_lib//lib:repositories.bzl", "bazel_lib_dependencies", "register_coreutils_toolchains")

bazel_lib_dependencies()

register_coreutils_toolchains()
