"Setup spawn_binary toolchain repositories and rules"

# https://github.com/bazel-contrib/bazel-lib/releases
load("//tools:integrity.bzl", "RELEASED_BINARY_INTEGRITY")
load("//tools:version.bzl", "VERSION")

# Platform names follow the platform naming convention in @bazel_lib//:lib/private/repo_utils.bzl
SPAWN_BINARY_PLATFORMS = {
    "darwin_amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "freebsd_amd64": struct(
        compatible_with = [
            "@platforms//os:freebsd",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_s390x": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:s390x",
        ],
    ),
    "windows_amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
    "windows_arm64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:arm64",
        ],
    ),
}

SpawnBinaryInfo = provider(
    doc = "Provide info for executing spawn_binary",
    fields = {
        "bin": "Executable spawn_binary binary",
    },
)

def _spawn_binary_toolchain_impl(ctx):
    binary = ctx.executable.bin

    default_info = DefaultInfo(
        files = depset([binary]),
        runfiles = ctx.runfiles(files = [binary]),
    )
    spawn_binary_info = SpawnBinaryInfo(
        bin = binary,
    )

    # Export all the providers inside our ToolchainInfo
    # so the resolved_toolchain rule can grab and re-export them.
    toolchain_info = platform_common.ToolchainInfo(
        spawn_binary_info = spawn_binary_info,
        default = default_info,
    )

    return [default_info, toolchain_info]

spawn_binary_toolchain = rule(
    implementation = _spawn_binary_toolchain_impl,
    attrs = {
        "bin": attr.label(
            mandatory = True,
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
)

def _spawn_binary_toolchains_repo_impl(rctx):
    # Expose a concrete toolchain which is the result of Bazel resolving the toolchain
    # for the execution or target platform.
    # Workaround for https://github.com/bazelbuild/bazel/issues/14009
    starlark_content = """# @generated by @bazel_lib//lib/private:spawn_binary_toolchain.bzl

# Forward all the providers
def _resolved_toolchain_impl(ctx):
    toolchain_info = ctx.toolchains["@bazel_lib//lib:spawn_binary_toolchain_type"]
    return [
        toolchain_info,
        toolchain_info.default,
        toolchain_info.spawn_binary_info,
        toolchain_info.template_variables,
    ]

# Copied from java_toolchain_alias
# https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/java_toolchain_alias.bzl
resolved_toolchain = rule(
    implementation = _resolved_toolchain_impl,
    toolchains = ["@bazel_lib//lib:spawn_binary_toolchain_type"],
)
"""
    rctx.file("defs.bzl", starlark_content)

    build_content = """# @generated by @bazel_lib//lib/private:spawn_binary_toolchain.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the spawn_binary_register_toolchains macro
# so you don't normally need to interact with these targets.

load(":defs.bzl", "resolved_toolchain")

resolved_toolchain(name = "resolved_toolchain", visibility = ["//visibility:public"])

"""

    for [platform, meta] in SPAWN_BINARY_PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:spawn_binary_toolchain",
    toolchain_type = "@bazel_lib//lib:spawn_binary_toolchain_type",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", build_content)

spawn_binary_toolchains_repo = repository_rule(
    _spawn_binary_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _spawn_binary_platform_repo_impl(rctx):
    is_windows = rctx.attr.platform.startswith("windows_")
    meta = SPAWN_BINARY_PLATFORMS[rctx.attr.platform]
    release_platform = meta.release_platform if hasattr(meta, "release_platform") else rctx.attr.platform
    release_file = "spawn_binary-{}{}".format(release_platform, ".exe" if is_windows else "")

    # https://github.com/bazel-contrib/bazel-lib/releases/download/v1.19.0/spawn_binary-linux_amd64
    url = "https://github.com/bazel-contrib/bazel-lib/releases/download/v{}/{}".format(
        VERSION,
        release_file,
    )

    rctx.download(
        url = url,
        output = "spawn_binary.exe" if is_windows else "spawn_binary",
        executable = True,
        sha256 = RELEASED_BINARY_INTEGRITY[release_file],
    )
    build_content = """# @generated by @bazel_lib//lib/private:spawn_binary_toolchain.bzl
load("@bazel_lib//lib/private:spawn_binary_toolchain.bzl", "spawn_binary_toolchain")
exports_files(["{0}"])
spawn_binary_toolchain(name = "spawn_binary_toolchain", bin = "{0}", visibility = ["//visibility:public"])
""".format("spawn_binary.exe" if is_windows else "spawn_binary")

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", build_content)

    # Bazel <8.3.0 lacks rctx.repo_metadata
    if not hasattr(rctx, "repo_metadata"):
        return None

    return rctx.repo_metadata(reproducible = True)

spawn_binary_platform_repo = repository_rule(
    implementation = _spawn_binary_platform_repo_impl,
    doc = "Fetch external tools needed for spawn_binary toolchain",
    attrs = {
        "platform": attr.string(mandatory = True, values = SPAWN_BINARY_PLATFORMS.keys()),
    },
)
